# Generated by Django 4.2.13 on 2024-08-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='labrary',
            new_name='library',
        ),
    ]
