db:
	python manage.py makemigrations
	python manage.py migrate

server:
	python manage.py runserver

git:
	git add .
	git commit -m "Added Comment model to the blog that allows users to comment on post"
	git push